# Generated by Django 5.2.1 on 2025-05-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='year',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='salary',
            name='month',
        ),
    ]
