# Generated by Django 5.2.1 on 2025-05-24 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_salary_unique_together_alter_salary_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal Fixo')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início (Primeiro Mês)')),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='installments_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Parcelas'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_installment',
            field=models.BooleanField(default=False, verbose_name='É Parcelado?'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Compra'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Mensal (para o ano todo)'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='year',
            field=models.PositiveIntegerField(unique=True, verbose_name='Ano'),
        ),
        migrations.CreateModel(
            name='FixedExpenseOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occurrence_date', models.DateField()),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('fixed_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='expenses.fixedexpense')),
            ],
            options={
                'verbose_name': 'Ocorrência de Gasto Fixo',
                'verbose_name_plural': 'Ocorrências de Gastos Fixos',
                'ordering': ['occurrence_date'],
            },
        ),
    ]
