# Generated by Django 5.2.1 on 2025-06-01 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_user_alter_fixedexpense_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Salário', 'verbose_name_plural': 'Salários'},
        ),
        migrations.AlterField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Ano'),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('user', 'year')},
        ),
    ]
