# Generated by Django 5.2.1 on 2025-06-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
