# Generated by Django 5.2.1 on 2025-06-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_rename_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
